use_frameworks!

platform :ios, '8.0'

target 'GuideBottomShowView_Example' do
  pod 'GuideBottomShowView', :path => '../'

  target 'GuideBottomShowView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
